version: "3.2"
#@FOR /f "tokens=*" %i IN ('docker-machine env --shell cmd box') DO @%i
services:

  postgres:
    build:
      context: ../
      dockerfile: src/db/Dockerfile
    ports:
      - "10001:5432"

  api:
    build:
      context: ../
      dockerfile: src/api/Dockerfile
    environment:
      - GP_SERVICE=api
      - GP_VERSION=local
      - GP_DATABASE_HOST=postgres
      - GP_DATABASE_USER=postgres
      - GP_DATABASE_PASSWORD=postgres
      - GP_DATABASE_PORT=5432
      - GP_DATABASE_DB=postgres
      - GP_ACCOUNT_SIGNUP_ENABLED=true
    ports:
      - "10002:8080"
